postgres:
  image: postgres:latest
  container_name: postgres_petapoco
  ports:
    - "5001:5432"
  environment:
    - POSTGRES_PASSWORD=petapoco
    - POSTGRES_USER=petapoco
mysql:
  image: mysql:latest
  container_name: mysql_petapoco
  ports:
    - "5002:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=petapoco
    - MYSQL_DATABASE=petapoco
    - MYSQL_PASSWORD=petapoco
    - MYSQL_USER=petapoco 